jobs:
  spellcheck:
    name: rojopolis/spellcheck
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: actions/checkout
      uses: actions/checkout@v2
    - continue-on-error: true
      name: rojopolis/spellcheck - actually doing something
      uses: rojopolis/spellcheck-github-actions@0.29.0
name: Checking for spelling errors
on:
  repository_dispatch:
    types: trigger-ga___spellcheck.yaml
